services:
  mysql:
    image: mysql:8.0
    container_name: mysql-laravel
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_react_messenger
    ports:
      - "3306:3306"
    volumes:
      - db_data_messenger:/var/lib/mysql

volumes:
  db_data_messenger:
